import Joi from 'joi';

export const employeeSchema = Joi.object({
  employeeNumber: Joi.string().required(),
  firstName: Joi.string().required(),
  lastName: Joi.string().required(),
  panNumber: Joi.string().required(),
  aadhaar: Joi.string().optional(),
  roleId: Joi.string().required(),
  departmentId: Joi.string().required(),
  designationId: Joi.string().required(),
  gender: Joi.string().valid('Male', 'Female', 'Other').required(),
  email: Joi.string().email().required(),
  dateOfBirth: Joi.date().required(),
  dateOfJoining: Joi.date().required(),
  bloodGroup: Joi.string().optional(),
  contactNumber: Joi.string().required(),
  education: Joi.string().optional(),
  assignShift: Joi.string().optional(),
  address: Joi.string().optional(),
  profilePhotoUrl: Joi.string().optional(),
  employmentType: Joi.string().valid('Permanent', 'Contract', 'Temporary').required(),
  basicPay: Joi.number().required(),
  ItDeclarationPerYear: Joi.number().optional(),
  netAmount: Joi.number().required(),
  allowanceDA: Joi.number().optional(),
  allowanceHRA: Joi.number().optional(),
  deductionPTax: Joi.number().optional(),
  organizationId: Joi.number().optional(),
});